pub mod project_detector;
pub mod amg;
pub mod cache;
pub mod aggregator;
pub mod java_source_roots;
pub mod go_module_roots;
pub mod rust_crate_roots;
pub mod c4_generator;
pub mod supplementary_diagrams;